In [1]:
import numpy as np

In [2]:
data = np.arange(9).reshape(3,3)
data1 = np.random.permutation(data)
print(data)
print("-"*20)
print(data1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
--------------------
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [3]:
data = np.arange(12).reshape(3,4)
res = np.random.shuffle(data) #shuffle直接改变原数据，所以没有返回值
print(res)
print(data)

None
[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [4]:
#完全打乱
data = np.arange(9).reshape(3,3)
data = data.reshape(-1)
res = np.random.permutation(data).reshape(3,3)
res

array([[1, 3, 4],
       [2, 5, 0],
       [8, 7, 6]])