In [1]:
import numpy as np

In [2]:
#生范围在1到10的随机数8个，这里允许有重复值
data = np.random.randint(1,10,(8)) #start，end，shape
print(data)

[4 2 1 9 1 3 2 4]


In [3]:
#生范围在0到10的随机数8个，replace=False表示没有重复数值，为True时则可以有重复
data_2 = np.random.choice(10,8,replace=False)
print(data_2)
data_3 = np.random.choice(10,8,replace=True)
print(data_3)
#这里的第一个参数也可以是一个列表
list1 = list("abcdefghijklmn")
data_4 = np.random.choice(list1,8,replace=False) #从list1里随机取8个值，无重复
print(data_4)

[6 5 8 4 3 2 0 1]
[7 9 3 5 2 5 5 2]
['d' 'b' 'e' 'i' 'k' 'f' 'h' 'g']
