In [1]:
import time

In [8]:
#时间戳形式：
# 1544771482.7639842
#时间元组形式：
# time.struct_time(tm_year=2018, tm_mon=12, tm_mday=14, tm_hour=14, tm_min=55, tm_sec=2, tm_wday=4, tm_yday=348, tm_isdst=0)

# 得到时间戳
timeStamp_1 = time.time()
print(timeStamp_1)
# 得到时间元组
timeTuple_1 = time.localtime() #无参数默认以当前时间戳来处理
print(timeTuple_1)

# 时间戳转时间元组
timeTuple_2 = time.localtime(timeStamp_1)
print(timeTuple_2)
# 时间元组转时间戳
timeStamp_2 = time.mktime(timeTuple_2)
print(timeStamp_2)

1544771521.5637908
time.struct_time(tm_year=2018, tm_mon=12, tm_mday=14, tm_hour=15, tm_min=12, tm_sec=1, tm_wday=4, tm_yday=348, tm_isdst=0)
time.struct_time(tm_year=2018, tm_mon=12, tm_mday=14, tm_hour=15, tm_min=12, tm_sec=1, tm_wday=4, tm_yday=348, tm_isdst=0)
1544771521.0


In [18]:
# 给定时间字符串，转换成时间元组 : strptime
# 需要指定时间形式
str_1 = "2018/12/14 15:12:1"
str_2 = "15:12:1 2018/12/14"
str_3 = "2018-12-14"
str_4 = "15:12:10"
time_tuple_1 = time.strptime(str_1,"%Y/%m/%d %H:%M:%S")
time_tuple_2 = time.strptime(str_2,"%H:%M:%S %Y/%m/%d")
time_tuple_3 = time.strptime(str_3,"%Y-%m-%d")
time_tuple_4 = time.strptime(str_4,"%H:%M:%S")
print(time_tuple_1)
print(time_tuple_2)
print(time_tuple_3)
print(time_tuple_4)
print(time_tuple_1[:3])
print(time_tuple_1[4])
print(type(time_tuple_1))

time.struct_time(tm_year=2018, tm_mon=12, tm_mday=14, tm_hour=15, tm_min=12, tm_sec=1, tm_wday=4, tm_yday=348, tm_isdst=-1)
time.struct_time(tm_year=2018, tm_mon=12, tm_mday=14, tm_hour=15, tm_min=12, tm_sec=1, tm_wday=4, tm_yday=348, tm_isdst=-1)
time.struct_time(tm_year=2018, tm_mon=12, tm_mday=14, tm_hour=0, tm_min=0, tm_sec=0, tm_wday=4, tm_yday=348, tm_isdst=-1)
time.struct_time(tm_year=1900, tm_mon=1, tm_mday=1, tm_hour=15, tm_min=12, tm_sec=10, tm_wday=0, tm_yday=1, tm_isdst=-1)
(2018, 12, 14)
12
<class 'time.struct_time'>


In [17]:
# 给定时间元组，转换成字符串 : strftime
time_tuple = time.localtime()
time_str_1 = time.strftime("%Y/%m/%d %H:%M:%S %A",time_tuple)
time_str_2 = time.strftime("%H:%M:%S %Y/%m/%d",time_tuple)
time_str_3 = time.strftime("%Y-%m-%d",time_tuple)
time_str_4 = time.strftime("%a %H:%M:%S",time_tuple)
print(time_str_1)
print(time_str_2)
print(time_str_3)
print(time_str_4)

2018/12/14 15:31:57 Friday
15:31:57 2018/12/14
2018-12-14
Fri 15:31:57


In [19]:
# 将 “2018/12/14 15:31:57 Friday” 修改成 "15:31:57 2018-12-14"
#分两步，第一步，将字符串转时间元组，strptime。第二步，将时间元组转字符串，并指定输出形式,strftime。
str_time = "2018/12/14 15:31:57 Friday"
temp_tuple = time.strptime(str_time,"%Y/%m/%d %H:%M:%S %A")
new_str_time = time.strftime("%H:%M:%S %Y-%m-%d",temp_tuple)
print(new_str_time)

15:31:57 2018-12-14


In [2]:
import numpy as np

In [24]:
#初始化矩阵
vec_1 = np.array([[1,2,3],[4,5,6]])
vec_2 = np.arange(1,7).reshape(2,3)
vec_3 = np.zeros(3) #一维
vec_4 = np.zeros((2,3))
vec_5 = np.ones(2)
vec_6 = np.ones((2,3))

print(vec_1,"\n","="*10)
print(vec_2,"\n","="*10)
print(vec_3,"\n","="*10)
print(vec_4,"\n","="*10)
print(vec_5,"\n","="*10)
print(vec_6,"\n","="*10)

[[1 2 3]
 [4 5 6]] 
[[1 2 3]
 [4 5 6]] 
[0. 0. 0.] 
[[0. 0. 0.]
 [0. 0. 0.]] 
[1. 1.] 
[[1. 1. 1.]
 [1. 1. 1.]] 
[[1. 0.]
 [0. 1.]] 


In [10]:
array_1 = np.arange(6).reshape(2,3) #生成0到6的数，尺寸为2行3列
array_1_1 = np.arange(1,7).reshape(2,3) #生成1到7之间的数，重排尺寸为2行3列
array_1_2 = np.arange(2,10,2).reshape(2,2) #生成2到10之间的数，步长为2，重排尺寸为2行2列
array_2 = np.linspace(1,7,7)   #等差数列，1到7，默认包含右边值，共要7个数，若要不包含，则endpoint=False
array_3 = np.logspace(0,4,3,base=2)  #等比数列，2的0次到2的4次，共要3个数，base控制底数，默认为10
array_4 = np.random.random((2,3)) #生成0到1之间的随机数，尺寸为2行3列
array_5 = np.random.rand(2,3) #和上面一个等价，但是可以少写一层括号
array_6 = np.random.randint(1,10,(2,3)) #生成1到10之间的随机数，尺寸为2行3列
print(array_1,"\n","="*10)
print(array_1_1,"\n","="*10)
print(array_1_2,"\n","="*10)
print(array_2,"\n","="*10)
print(array_3,"\n","="*10)
print(array_4,"\n","="*10)
print(array_5,"\n","="*10)
print(array_6,"\n","="*10)

[[0 1 2]
 [3 4 5]] 
[[1 2 3]
 [4 5 6]] 
[[2 4]
 [6 8]] 
[1. 2. 3. 4. 5. 6. 7.] 
[ 1.  4. 16.] 
[[0.60100381 0.18638079 0.3871607 ]
 [0.82379782 0.18471237 0.65749406]] 
[[0.94482949 0.73528298 0.16618219]
 [0.89547714 0.46218512 0.64290658]] 
[[3 1 6]
 [2 6 1]] 


In [15]:
vec_1 = np.identity(2)  #单位矩阵
vec_2 = np.diag((1,2,3)) #对角矩阵，元素分别为1，2，3
vec_3 = np.mat("1,2;3,4;5,6")  #mat之后变成矩阵，可以进行矩阵点积运算
vec_4 = np.dot(vec_2,vec_3) #dot为点积运算
vec_5 = vec_3.I   #I表示求逆矩阵
vec_6 = vec_3.T   #T表示求转置
print(vec_1,"\n","="*10)
print(vec_2,"\n","="*10)
print(vec_3,"\n","="*10)
print(vec_3.shape)
print(vec_4,"\n","="*10)
print(vec_5,"\n","="*10)
print(vec_6,"\n","="*10)

[[1. 0.]
 [0. 1.]] 
[[1 0 0]
 [0 2 0]
 [0 0 3]] 
[[1 2]
 [3 4]
 [5 6]] 
(3, 2)
[[ 1  2]
 [ 6  8]
 [15 18]] 
[[-1.33333333 -0.33333333  0.66666667]
 [ 1.08333333  0.33333333 -0.41666667]] 
[[1 3 5]
 [2 4 6]] 


In [19]:
#numpy之间基本运算
#每个元素的对应操作
arr_1 = np.array([1,2,3,4,5])
print(arr_1+3)
print(arr_1*2)
print(10/arr_1)
print(arr_1**2)
print(2**arr_1)
print("="*20)
#对应元素操作
arr_2 = np.array([5,4,3,2,1])
print(arr_1+arr_2)
print(arr_1-arr_2)
print(arr_1*arr_2)
print(arr_1/arr_2)
print(arr_1**arr_2)

[4 5 6 7 8]
[ 2  4  6  8 10]
[10.          5.          3.33333333  2.5         2.        ]
[ 1  4  9 16 25]
[ 2  4  8 16 32]
[6 6 6 6 6]
[-4 -2  0  2  4]
[5 8 9 8 5]
[0.2 0.5 1.  2.  5. ]
[ 1 16 27 16  5]


In [28]:
#广播
#若一个矩阵维度是a*b,另一个矩阵或者是a*b，或者是b，都可以运算。
#       若是a*b，则对应元素运算，若是b，则为广播
#若一个矩阵维度是a*b*c,则另一个矩阵或者是a*b*c，或者是b*c，或者是c，都可以运算，第一个是对应元素运算，后面两个是广播。

arr1 = np.array([[1,2,3],[5,6,7]]) #维度是2*3
arr2 = np.array([5,4,3]) #维度是3
print(arr1+arr2,"\n","="*10) #一个是2*3，一个是3，所以可以运算，即广播运算
print(arr1*arr2,"\n","="*10) #对运算符号没有要求，只是尺寸的问题，故而对应元素乘等也是一样

arr3 = np.arange(6).reshape(1,2,3)
arr4 = np.array([1,2,3])
arr5 = np.arange(6).reshape(2,3)
print(arr3,"\n","="*10)
print(arr4,"\n","="*10)
print(arr5,"\n","="*10)
print(arr3+arr4,"\n","="*10)
print(arr3+arr5,"\n","="*10)

[[ 6  6  6]
 [10 10 10]] 
[[ 5  8  9]
 [25 24 21]] 
[[[0 1 2]
  [3 4 5]]] 
[1 2 3] 
[[0 1 2]
 [3 4 5]] 
[[[1 3 5]
  [4 6 8]]] 
[[[ 0  2  4]
  [ 6  8 10]]] 


In [39]:
#切片，选数
arr = np.arange(24).reshape(2,3,4)
print(arr,"\n","="*10)
# [[[ 0  1  2  3]
#   [ 4  5  6  7]
#   [ 8  9 10 11]]

#  [[12 13 14 15]
#   [16 17 18 19]
#   [20 21 22 23]]] 
#选择2，6，10
res_1 = arr[0][:,2]
print(res_1,"\n","="*10)
#选择1，5，9，13，17，21
res_2 = arr[:,:,1]
print(res_2,"\n","="*10)
#选择4，5，6，7
res_3 = arr[0][1]
print(res_3,"\n","="*10)
#选择8，9，10，11，20，21，22，23
res_4 = arr[:,-1,:]
print(res_4,"\n","="*10)
#选择5，6
res_5 = arr[0][1][1:3]
print(res_5,"\n","="*10)
#选择5，6，9，10
res_6 = arr[0][1:,1:3]
print(res_6,"\n","="*10)
#选择5，6，17，18
res_7 = arr[:,1,1:3]
print(res_7,"\n","="*10)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] 
[ 2  6 10] 
[[ 1  5  9]
 [13 17 21]] 
[4 5 6 7] 
[[ 8  9 10 11]
 [20 21 22 23]] 
[5 6] 
[[ 5  6]
 [ 9 10]] 
[[ 5  6]
 [17 18]] 


In [41]:
#拆分小数和整数
arr = np.array([1.2,2.3,3.4,4.5])
float_num,int_num = np.modf(arr)
print(int_num,float_num)

[1. 2. 3. 4.] [0.2 0.3 0.4 0.5]


In [46]:
arr = np.array([[1,2,3,4],[7,8,9,10]])
print(arr)
print(arr.min())
print(arr.max())
print(arr.mean())
print(arr.std())
print(np.sqrt(np.sum(np.power(arr-arr.mean(),2))/arr.size))
print(arr.mean(axis=0))
print(arr.sum(axis=1))

[[ 1  2  3  4]
 [ 7  8  9 10]]
1
10
5.5
3.2015621187164243
3.2015621187164243
[4. 5. 6. 7.]
[10 34]


In [48]:
#np.where(condition,A,B)
#condition表示条件，如果为True，则选择A中的值，否则选择B中的值
xarr = np.array([-1.1,-1.2,-1.3,1.4,-1.5])
yarr = np.array([-2.1,-2.2,2.3,2.4,-2.5])
condition = xarr < yarr
res_1 = [x if c else y for x,y,c in zip(xarr,yarr,condition)]   #list
res_2 = np.where(condition,xarr,yarr)   #ndarray
print(res_1)
print(res_2)

[-2.1, -2.2, -1.3, 1.4, -2.5]
[-2.1 -2.2 -1.3  1.4 -2.5]


In [50]:
#将异常值替换为0
arr = np.array([
    [1,2,np.NAN,4],
    [4,5,6,np.NAN],
    [7,8,9,np.Inf],
    [np.inf,np.e,np.pi,66]
])
condition = np.isnan(arr) | np.isinf(arr)
res = np.where(condition,0,arr) #condition为True时对应值为0，不然就选择arr对应的值
print(res)

[[ 1.          2.          0.          4.        ]
 [ 4.          5.          6.          0.        ]
 [ 7.          8.          9.          0.        ]
 [ 0.          2.71828183  3.14159265 66.        ]]


In [51]:
#去重
arr_1 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
arr_2 = np.array(['a','b','c','c','b'])
print(np.unique(arr_1))
print(np.unique(arr_2))

[1 2 3 4 5 6]
['a' 'b' 'c']


In [58]:
#排序1：直接排序
array = np.arange(10)
np.random.seed(1)
np.random.shuffle(array)
print(array)
sort_array = np.sort(array)
print(sort_array)
print(sort_array[-1:-4:-1]) #排序后倒数3个，即最大三个

[2 9 6 4 0 3 1 7 8 5]
[0 1 2 3 4 5 6 7 8 9]
[9 8 7]


In [59]:
#排序2：以索引排序
array = np.arange(10)
np.random.seed(1)
np.random.shuffle(array)
print(array)
sort_arr = np.argsort(array) #得到的也是从小到大的数，但是这个得到的是索引位置
print(sort_arr)
print(sort_arr[-1:-4:-1]) 
print(array[sort_arr])  #所以通过进一步用索引位也可以得到数的顺序
print(array[sort_arr[-1:-4:-1]])

[2 9 6 4 0 3 1 7 8 5]
[4 6 0 5 3 9 2 7 8 1]
[1 8 7]
[0 1 2 3 4 5 6 7 8 9]
[9 8 7]


In [63]:
#找对应位置，arg
array = np.arange(10)[-1::-1]
print(array)
print(np.argmax(array))
print(np.argmin(array))
print(np.argsort(array))   #找到从小到大的数对应的索引位
print(array[np.argsort(array)])   #对元素进行排序，返回的是对应索引位置

[9 8 7 6 5 4 3 2 1 0]
0
9
[9 8 7 6 5 4 3 2 1 0]
[0 1 2 3 4 5 6 7 8 9]


In [1]:
import pandas as pd
#pandas里主要有series和dataframe
#其中series是类似于一维数组的结构，即只有一组数据以及其相应的标签组成
#而dataframe则类似于表格，可以有多组数据，既有行索引，也有列索引

In [7]:
arr = np.array([1,3,5,np.NAN,10])
series_1 = pd.Series(arr)
print(series_1,"\n","="*10)
print(series_1.values,"\n","="*10)
print(series_1.dtype,"\n","="*10)
print(series_1.index,"\n","="*10)

0     1.0
1     3.0
2     5.0
3     NaN
4    10.0
dtype: float64 
[ 1.  3.  5. nan 10.] 
float64 
RangeIndex(start=0, stop=5, step=1) 


In [15]:
#单项设定，分布初始化
series_2 = pd.Series([90,91,92])
series_2.index = [u'语文',u'数学',u'英语']
print(series_2,"\n","="*10)
#以一次性设定所有属性值来初始化
series_3 = pd.Series(data=[90,91,92],index=[u'语文',u'数学',u'英语'],dtype=np.int64)
print(series_3,"\n","="*10)
#以字典的形式创建
num_dict = {u'语文':92,u'数学':93,u'英语':94}
series_4 = pd.Series(num_dict)
print(series_4,"\n","="*10)

语文    90
数学    91
英语    92
dtype: int64 
语文    90
数学    91
英语    92
dtype: int64 
数学    93
英语    94
语文    92
dtype: int64 


In [19]:
#series的一些属性
series_3 = pd.Series(data=[90,91,92],index=[u'语文',u'数学',u'英语'],dtype=np.int64)
print(series_3,"\n","="*10)
series_3.name = "series_3"
series_3.index.name = "series_3_index"
print(series_3.axes,"\n","="*10) #打印出表信息
print(series_3.size,"\n","="*10) #返回表个数
print(series_3.head(2),"\n","="*10)
print(series_3.tail(2),"\n","="*10)

语文    90
数学    91
英语    92
dtype: int64 
[Index(['语文', '数学', '英语'], dtype='object', name='series_3_index')] 
3 
series_3_index
语文    90
数学    91
Name: series_3, dtype: int64 
series_3_index
数学    91
英语    92
Name: series_3, dtype: int64 


In [18]:
#series值的获取
series_3 = pd.Series(data=[90,91,92],index=[u'语文',u'数学',u'英语'],dtype=np.int64)
print(series_3,"\n","="*10)
print(series_3[u'语文'],"\n","="*10)
print(series_3[0],"\n","="*10)
print(series_3[-1],"\n","="*10)
print(series_3[0:-1],"\n","="*10)
print(series_3[u'语文':u'英语'],"\n","="*10)

语文    90
数学    91
英语    92
dtype: int64 
90 
90 
92 
语文    90
数学    91
dtype: int64 
语文    90
数学    91
英语    92
dtype: int64 
