In [1]:
#   permutation的作用是随机打乱已有数据顺序
#   它和shuffle的区别是：shuffle会改变原数据，而permutation不会改变原数据
#   对于一维数组是完全打乱
#   但是对于多维数组，比如二维数组，shuffle和permutation都是整体不变，只打乱第一个维度
#   故而对于多个样本数据，每个样本数据有多维时，可以用这两个来进行打乱

In [2]:
import numpy as np

In [3]:
data = np.arange(9).reshape(3,3)
data1 = np.random.permutation(data)
print(data)
print("-"*20)
print(data1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
--------------------
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
data = np.arange(12).reshape(3,4)
res = np.random.shuffle(data) #shuffle直接改变原数据，所以没有返回值
print(res)
print(data)

None
[[ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]]


In [5]:
#完全打乱
data = np.arange(9).reshape(3,3)
data = data.reshape(-1)
res = np.random.permutation(data).reshape(3,3)
res

array([[6, 2, 5],
       [4, 0, 1],
       [7, 8, 3]])

In [6]:
#对两个或者多个list想要按照一个方式打乱顺序的话，也可以固定随机种子来实现
list1 = [chr(each) for each in range(97,97+26)]
list2 = [chr(each) for each in range(65,65+26)]
print("before:");print(list1);print(list2)
randomSeed = np.random.randint(0,len(list1))
np.random.seed(randomSeed)
np.random.shuffle(list1)
np.random.seed(randomSeed)
np.random.shuffle(list2)
print("after:");print(list1);print(list2)

before:
['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
after:
['s', 'o', 'e', 'x', 'a', 'p', 'h', 'g', 'l', 'c', 'w', 'k', 'z', 'b', 'm', 'v', 'n', 'q', 'y', 't', 'i', 'f', 'j', 'r', 'u', 'd']
['S', 'O', 'E', 'X', 'A', 'P', 'H', 'G', 'L', 'C', 'W', 'K', 'Z', 'B', 'M', 'V', 'N', 'Q', 'Y', 'T', 'I', 'F', 'J', 'R', 'U', 'D']


In [7]:
#优先这种方式
# 如果想要同时对ndarray和list打乱顺序，并且是一个套路的话。
# 则可以都转换成ndarray，然后整体使用打乱顺序的下标。在深度学习中样本打乱比较常用
x1 = np.arange(0,50).reshape(5,10)
x2 = np.arange(50,100).reshape(5,10)
y = list(np.random.randint(0,2,(5,)))
#这里即x1和x2是矩阵，y是列表，即创建原始表
print("before");print(x1,"\n","="*20);print(x2,"\n","="*20);print(y,"\n","="*20);print("After")
shuffle_idx = np.random.permutation(np.arange(len(y)))
x1_shuffled = np.asarray(x1)[shuffle_idx]
x2_shuffled = np.asarray(x2)[shuffle_idx]
y_shuffled = np.asarray(y)[shuffle_idx]
print(x1_shuffled,"\n","="*20);print(x2_shuffled,"\n","="*20);print(y_shuffled,"\n","="*20)
#这里即将三者按照一个标准打乱顺序，重点即先转成ndarray格式

before
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]] 
[[50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]] 
[1, 1, 1, 0, 1] 
After
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [20 21 22 23 24 25 26 27 28 29]] 
[[50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]
 [70 71 72 73 74 75 76 77 78 79]] 
[1 1 0 1 1] 
