In [1]:
#   permutation的作用是随机打乱已有数据顺序
#   它和shuffle的区别是：shuffle会改变原数据，而permutation不会改变原数据
#   对于一维数组是完全打乱
#   但是对于多维数组，比如二维数组，shuffle和permutation都是整体不变，只打乱第一个维度
#   故而对于多个样本数据，每个样本数据有多维时，可以用这两个来进行打乱

In [2]:
import numpy as np

In [3]:
data = np.arange(9).reshape(3,3)
data1 = np.random.permutation(data)
print(data)
print("-"*20)
print(data1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
--------------------
[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [4]:
data = np.arange(12).reshape(3,4)
res = np.random.shuffle(data) #shuffle直接改变原数据，所以没有返回值
print(res)
print(data)

None
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [5]:
#完全打乱
data = np.arange(9).reshape(3,3)
data = data.reshape(-1)
res = np.random.permutation(data).reshape(3,3)
res

array([[8, 4, 0],
       [1, 2, 3],
       [5, 6, 7]])

In [6]:
#实际应用中，比较好用的方式是获得打乱的序号再赋值
#属于是整体样本打乱顺序，但是样本中原句子或原字信息顺序不变，这个对列表不行，列表就直接permutation或者shuffle即可
ndarray = np.arange(0,100).reshape(10,10)
print(ndarray,"\n","="*40)
shuffle_idx = np.random.permutation(np.arange(len(ndarray)))
ndarray_shuffled = ndarray[shuffle_idx]
print(ndarray_shuffled)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]] 
[[90 91 92 93 94 95 96 97 98 99]
 [30 31 32 33 34 35 36 37 38 39]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [40 41 42 43 44 45 46 47 48 49]
 [ 0  1  2  3  4  5  6  7  8  9]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [20 21 22 23 24 25 26 27 28 29]
 [10 11 12 13 14 15 16 17 18 19]]


In [7]:
#对两个或者多个list想要按照一个方式打乱顺序的话，可以固定随机种子来实现
list1 = [chr(each) for each in range(97,97+26)]
list2 = [chr(each) for each in range(65,65+26)]
print("before:");print(list1);print(list2)
randomSeed = np.random.randint(0,len(list1))
np.random.seed(randomSeed)
np.random.shuffle(list1)
np.random.seed(randomSeed)
np.random.shuffle(list2)
print("after:");print(list1);print(list2)

before:
['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
after:
['t', 'f', 'o', 'h', 'b', 'c', 'l', 'x', 'n', 'm', 'u', 'd', 'y', 'g', 's', 'k', 'w', 'z', 'i', 'v', 'q', 'r', 'a', 'p', 'e', 'j']
['T', 'F', 'O', 'H', 'B', 'C', 'L', 'X', 'N', 'M', 'U', 'D', 'Y', 'G', 'S', 'K', 'W', 'Z', 'I', 'V', 'Q', 'R', 'A', 'P', 'E', 'J']
