In [4]:
#tf.nn.embedding_lookup

In [5]:
import tensorflow as tf
import numpy as np

D:\Anaconda\Initial\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [6]:
data = np.arange(10)
res = tf.nn.embedding_lookup(data, [1, 3])
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())#初始化session
    output = sess.run(res)
    print(data)
    print(output)

[0 1 2 3 4 5 6 7 8 9]
[1 3]


In [7]:
data1 = np.arange(12).reshape(4,3)
idx1 = tf.Variable([0, 2, 1], tf.int32) #1*3
idx2 = tf.constant([[0, 2, 1],[3, 0, 2]], tf.int32) #2*3
out1 = tf.nn.embedding_lookup(data1, idx1) 
out2 = tf.nn.embedding_lookup(data1, idx2) 
init = tf.global_variables_initializer() 
with tf.Session() as sess:
    sess.run(init)
    print(data1)
    print("-"*20)  
    print(sess.run(out1))   #取1回，每次取3个，而原数据data1是4*3，故而每个有3列，即最终为3*3
    print("-"*20)
    print(sess.run(out2))   #取2回，每次取3个，而原数据data1是4*3，故而每个有3列，即最终为2*3*3

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
--------------------
[[0 1 2]
 [6 7 8]
 [3 4 5]]
--------------------
[[[ 0  1  2]
  [ 6  7  8]
  [ 3  4  5]]

 [[ 9 10 11]
  [ 0  1  2]
  [ 6  7  8]]]
