In [1]:
#1、tf.get_variable()一般配合tf.variable_scope和reuse一起操作。
#   同一个scope，相同名字的变量需要resue才能使用
#2、tf.Variable()每次都会生成一个新的变量，故而即使重名也不会报错
#3、tf.Variable()必须给定初始化值，而tf.get_variable()则必须给定名字和大小

In [2]:
#几种初始化方式：
#1、常量初始化
#   initializer=tf.constant_initializer(2)
#   initializer=tf.constant_initializer(np.arange(6).reshape(2,3))
#2、正态分布初始化
#   tf.random_normal(shape=[2,3], mean=0, stddev=1)
#3、输入输出都服从均匀分布的初始化
#   initializer = initializers.xavier_initializer()     #from tensorflow.contrib.layers.python.layers import initializers

In [3]:
import tensorflow as tf
import numpy as np

D:\Anaconda\Initial\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [4]:
#最精简的初始化
a1 = tf.Variable(1)
a2 = tf.get_variable("a2",shape=[1])

In [5]:
#稍微细致一点的初始化
a1_2 = tf.Variable(initial_value=np.arange(9).reshape(3,3),name="a1_2",dtype=tf.int32)
a1_3 = tf.Variable(tf.random_normal(shape=[2,3], mean=0, stddev=1), name='a1_3')

a2_2 = tf.get_variable(name='a2_2', shape=[1], initializer=tf.constant_initializer(2),dtype=tf.int32)
a2_3 = tf.get_variable(name="a2_3",shape=[2,3], initializer=tf.constant_initializer(np.arange(6).reshape(2,3)))

In [6]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(a1.name,end=" ")
    print(a2.name)
    print(a1_2.name,end=" ")
    print(a1_3.name)
    print(a2_2.name)
    print(a2_3.name)
    print("-"*20)
    print(sess.run(a1))
    print(sess.run(a1_2))
    print(sess.run(a2))
    print(sess.run(a2_2))
    print(sess.run(a1_3))
    print(sess.run(a2_3))

Variable:0 a2:0
a1_2:0 a1_3:0
a2_2:0
a2_3:0
--------------------
1
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[-0.6339197]
[2]
[[ 0.40030128 -1.2955449   1.1548274 ]
 [ 1.6161565  -0.00228999 -0.10751949]]
[[0. 1. 2.]
 [3. 4. 5.]]


In [7]:
with tf.variable_scope("one"):
    a = tf.get_variable("v", [1]) #a.name == "one/v:0"
    
# with tf.variable_scope("one"):
#     b = tf.get_variable("v", [1]) #创建两个名字一样的变量会报错 ValueError: Variable one/v already exists 

with tf.variable_scope("one", reuse = True): #注意reuse的作用。
    c = tf.get_variable("v", [1]) #c.name == "one/v:0" 成功共享，因为设置了reuse
    
print(a==c) #Assertion is true, they refer to the same object.

True


In [8]:
#tf.Variable每次都会生成一个新的变量，故而即使重名也不会报错
a2 = tf.Variable(tf.random_normal(shape=[2,3], mean=0, stddev=1), name='a2')
a4 = tf.Variable(tf.random_normal(shape=[2,3], mean=0, stddev=1), name='a2')
print(a2 == a4)

False
