In [1]:
# tf.variable_scope可以让变量有相同的命名，包括tf.get_variable得到的变量，还有tf.Variable的变量
# tf.name_scope可以让变量有相同的命名，只是限于tf.Variable的变量
# 通过tf.get_variable方式获得的变量需要有一个初始化方式
#初始化方式：
#1、常量初始化： tf.constant_initializer() 
#2、输入输出相同概率分布初始化： tensorflow.contrib.layers.python.layers.initializers.xavier_initializer()

In [2]:
import tensorflow as tf

D:\Anaconda\Initial\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [3]:
with tf.variable_scope('V1'):
    a1 = tf.get_variable(name='a1', shape=[1], initializer=tf.constant_initializer(1))
    a2 = tf.Variable(tf.random_normal(shape=[2,3], mean=0, stddev=1), name='a2') #随机生成正态分布数据
with tf.variable_scope('V2'):
    a3 = tf.get_variable(name='a1', shape=[1], initializer=tf.constant_initializer(2))
    a4 = tf.Variable(tf.random_normal(shape=[2,3], mean=0, stddev=1), name='a2')
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(a1.name,end=" ")
    print(sess.run(a1))
    print(a2.name)
    print(a3.name,end=" ")
    print(sess.run(a3))
    print(a4.name)

V1/a1:0 [1.]
V1/a2:0
V2/a1:0 [2.]
V2/a2:0


In [4]:
with tf.name_scope('V1'):
    a1 = tf.get_variable(name='a1', shape=[1], initializer=tf.constant_initializer(1))
    a2 = tf.Variable(tf.random_normal(shape=[2,3], mean=0, stddev=1), name='a2')
with tf.name_scope('V2'):
    #a3 = tf.get_variable(name='a1', shape=[1], initializer=tf.constant_initializer(1)) 加上此行会报错，不允许tf.get_variable得到的变量有重名
    a4 = tf.Variable(tf.random_normal(shape=[2,3], mean=0, stddev=1), name='a2')
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(a1.name)
    print(a2.name)
    print(sess.run(a2))
    print(a4.name)
    print(sess.run(a4))

a1:0
V1_1/a2:0
[[-0.3744006  -0.04110023 -0.07917712]
 [-1.9478253   1.8827535  -0.34644288]]
V2_1/a2:0
[[-0.28441972 -0.99758637 -0.8507911 ]
 [-0.34146723 -1.8264812   0.82299984]]
