In [1]:
#在tensorflow中，主要是使用tf.stack()和tf.unstack()
#unstack默认即将第0个维度拆解,比如原本shape=[a*b*c]，拆解后即a*[b*c]
#而stack则是拼接,一般拼接和拆解也都是横向的,除非自己指定axis

In [2]:
import tensorflow as tf
import numpy as np

D:\Anaconda\Initial\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [3]:
a = tf.constant([1,2,3,4]) 
b = tf.constant([5,6,7,8]) 
c = tf.stack( [a,b], axis=0)  #横向拼接起来
d = tf.unstack(c,axis=0)   #横向拆解,默认即横向
e = tf.unstack(c,axis=1)   #纵向拆解

with tf.Session().as_default() as sess:
    sess.run(tf.global_variables_initializer())
    
print(sess.run(c),"\n","="*20)
print(sess.run(d),"\n","="*20)
print(sess.run(e),"\n","="*20)

x = tf.constant(np.arange(24).reshape(2,3,4))
print(sess.run(x),"\n","="*20)
x = tf.transpose(x,perm=[1,0,2])
print(sess.run(x),"\n","="*20)
x_unstackd = tf.unstack(x)
print(sess.run(x_unstackd),"\n","="*20)

[[1 2 3 4]
 [5 6 7 8]] 
[array([1, 2, 3, 4]), array([5, 6, 7, 8])] 
[array([1, 5]), array([2, 6]), array([3, 7]), array([4, 8])] 
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] 
[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]] 
[array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]]), array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]]), array([[ 8,  9, 10, 11],
       [20, 21, 22, 23]])] 
