In [31]:
import numpy as np
import pandas as pd

In [32]:
#定义一个简单的数据，使得数据符合y=x1+x2
df = pd.DataFrame({'x1':[1,2,3,4,5,6],'x2':[1,2,1,2,1,2],'y':[2,4,4,6,6,8],'y1':[4,8,8,12,12,16]})
x = df[['x1','x2']]
y = df['y'].values.reshape([-1,1])
y1 = df['y1'].values.reshape([-1,1])
df

x1  x2  y  y1
0   1   1  2   4
1   2   2  4   8
2   3   1  4   8
3   4   2  6  12
4   5   1  6  12
5   6   2  8  16

In [33]:
#使用直接计算法
import math
np.dot(np.mat(x.T.dot(x)).I,x.T).dot(y1)

matrix([[2.],
        [2.]])

In [34]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
#poly = PolynomialFeatures(degree=2,interaction_only=False,include_bias=False)
model = Pipeline([
        ('Poly', PolynomialFeatures()),
        ('Linear', LinearRegression(fit_intercept=False))
    ])


In [35]:
#批量梯度下降------初始化theta，给定一个alpha
theta = np.array([[0],[0]])
alpha = 0.01
theta

array([[0],
       [0]])

In [36]:
#批量梯度下降------迭代
the = 1e-6
max_iter = 500
for time in range(max_iter):
    theta = theta - alpha * x.T.dot(x.dot(theta)-y)
    loss = np.power(x.dot(theta)-y,2).sum()
    print('loss值为%f \ntheta值为\n'%loss,theta.values)
    if loss[0] < the:
        break

loss值为1.060800 
theta值为
 [[1.24]
 [0.48]]
loss值为0.825504 
theta值为
 [[1.1932]
 [0.4788]]
loss值为0.781794 
theta值为
 [[1.189384]
 [0.493224]]
loss值为0.740587 
theta值为
 [[1.18428064]
 [0.50674368]]
loss值为0.701552 
theta值为
 [[1.17935984]
 [0.51991952]]
loss值为0.664575 
theta值为
 [[1.17456895]
 [0.53274284]]
loss值为0.629546 
theta值为
 [[1.16990607]
 [0.54522366]]
loss值为0.596364 
theta值为
 [[1.16536774]
 [0.55737111]]
loss值为0.564931 
theta值为
 [[1.16095063]
 [0.56919409]]
loss值为0.535154 
theta值为
 [[1.15665151]
 [0.58070127]]
loss值为0.506947 
theta值为
 [[1.15246722]
 [0.59190108]]
loss值为0.480227 
theta值为
 [[1.14839469]
 [0.60280174]]
loss值为0.454915 
theta值为
 [[1.14443095]
 [0.61341123]]
loss值为0.430937 
theta值为
 [[1.14057308]
 [0.62373733]]
loss值为0.408223 
theta值为
 [[1.13681826]
 [0.63378762]]
loss值为0.386707 
theta值为
 [[1.13316373]
 [0.64356945]]
loss值为0.366324 
theta值为
 [[1.12960682]
 [0.65309   ]]
loss值为0.347016 
theta值为
 [[1.12614491]
 [0.66235625]]
loss值为0.328725 
theta值为
 [[1.12277548]
 [0.67137499]

 [[1.00099122]
 [0.99734687]]
loss值为0.000020 
theta值为
 [[1.00096474]
 [0.99741774]]
loss值为0.000019 
theta值为
 [[1.00093897]
 [0.99748671]]
loss值为0.000018 
theta值为
 [[1.00091389]
 [0.99755385]]
loss值为0.000017 
theta值为
 [[1.00088948]
 [0.99761918]]
loss值为0.000016 
theta值为
 [[1.00086572]
 [0.99768278]]
loss值为0.000015 
theta值为
 [[1.0008426 ]
 [0.99774467]]
loss值为0.000015 
theta值为
 [[1.00082009]
 [0.99780491]]
loss值为0.000014 
theta值为
 [[1.00079819]
 [0.99786355]]
loss值为0.000013 
theta值为
 [[1.00077687]
 [0.99792061]]
loss值为0.000012 
theta值为
 [[1.00075612]
 [0.99797616]]
loss值为0.000012 
theta值为
 [[1.00073592]
 [0.99803021]]
loss值为0.000011 
theta值为
 [[1.00071626]
 [0.99808283]]
loss值为0.000011 
theta值为
 [[1.00069713]
 [0.99813404]]
loss值为0.000010 
theta值为
 [[1.00067851]
 [0.99818388]]
loss值为0.000010 
theta值为
 [[1.00066039]
 [0.99823239]]
loss值为0.000009 
theta值为
 [[1.00064275]
 [0.9982796 ]]
loss值为0.000009 
theta值为
 [[1.00062558]
 [0.99832556]]
loss值为0.000008 
theta值为
 [[1.00060887]
 [0.99837028]

In [7]:
#随机梯度下降------初始化theta，给定一个alpha
df_s = df.sample(frac=1).values
x_s = df_s[:,0:2]
y = df_s[:,2]
theta_s = np.array([0,0])
alpha_s = 0.01

In [15]:
#随机梯度下降------迭代
for i in range(6):
    theta_s = theta_s - alpha_s * (x_s[i].dot(theta_s)-y[i])*x_s[i]
    loss = np.power(x_s.dot(theta_s)-y,2).sum()
    print('loss值为%f theta值为\n'%loss,theta_s)

loss值为0.788115 theta值为
 [1.15630901 0.50588558]
loss值为0.760788 theta值为
 [1.15968706 0.50926363]
loss值为0.691524 theta值为
 [1.17292904 0.5225056 ]
loss值为0.689923 theta值为
 [1.18345994 0.52777106]
loss值为0.686952 theta值为
 [1.18111542 0.52698955]
loss值为0.686691 theta值为
 [1.17267512 0.52417612]


In [16]:
#小批量梯度下降------初始化theta，给定一个alpha
theta_m = np.array([0,0])
alpha_m = 0.03

In [17]:
#小批量梯度下降------迭代
flag = True
for i in range(3):
    theta_m = theta_m - alpha_m * x[i:i+2].T.dot(x[i:i+2].dot(theta_m)-y[i:i+2])
    loss = np.power(x.dot(theta_m)-y,2).sum()
    print('loss值为%f theta值为\n'%loss,theta_m.values)   

loss值为91.480000 theta值为
 [0.3 0.3]
loss值为48.122560 theta值为
 [0.6   0.432]
loss值为24.862792 theta值为
 [1.08744 0.6492 ]


# 自己练习

In [1]:
import numpy as np
import pandas as pd

In [3]:
# y = x1 + x2
df = pd.DataFrame({'x1':[1,2,3,4,5,6],'x2':[1,2,1,2,1,2],'y':[2,4,4,6,6,8]})
df

x1  x2  y
0   1   1  2
1   2   2  4
2   3   1  4
3   4   2  6
4   5   1  6
5   6   2  8

In [4]:
x = df[['x1','x2']]
x = x.values.reshape(-1,2)
y = df['y']
y = y.values.reshape(-1,1)
print(y.shape)
theta = np.mat(x.T.dot(x)).I.dot(x.T).dot(y)
print(theta)

(6, 1)
[[1.]
 [1.]]


In [566]:
#批量梯度下降算法 BGD 
#初始化theta和alpha
theta = np.array([[0],[0]])
alpha = 0.01

In [746]:
the_end = 1e-6
max_iter = 500
for time in range(max_iter):
    theta = theta - alpha*x.T.dot(x.dot(theta)-y)
    loss = np.power(x.dot(theta)-y,2).sum()/2
    print("loss值为%f\n theta值为\n"%loss,theta)
    if loss < the_end:
        break

loss值为0.000000
 theta值为
 [[1.00000026]
 [0.99999929]]


In [568]:
#随机梯度下降算法 
#初始化theta，alpha
theta_s = np.array([[0],[0]])
alpha_s = 0.01

In [569]:
#这里其实也需要和上一个一样，设置一个max_iter，不断重复直至收敛，即外层还需套一层循环，光遍历完一遍所有的还不够
for i in range(6):
    theta_s = theta_s-alpha_s * (x[i].dot(theta_s)-y[i])*x[i]
    loss = np.power(x[i].dot(theta_s)-y[i],2).sum()/2
    print("loss:%f\n theta:"%loss,theta_s)

loss:7.683200
 theta: [[0.02 0.02]
 [0.02 0.02]]
loss:26.012242
 theta: [[0.0984 0.0984]
 [0.0984 0.0984]]
loss:22.058381
 theta: [[0.206592 0.134464]
 [0.206592 0.134464]]
loss:33.974668
 theta: [[0.39700992 0.23832832]
 [0.39700992 0.23832832]]
loss:24.867992
 theta: [[0.57790694 0.28402862]
 [0.57790694 0.28402862]]
loss:26.232084
 theta: [[0.78051161 0.39858404]
 [0.78051161 0.39858404]]


In [550]:
#小批量梯度下降
#初始化theta和alpha
theta_m = np.array([[0],[0]])
alpha_m = 0.01

In [745]:
#这里其实也需要和上一个一样，设置一个max_iter，不断重复直至收敛，即外层还需套一层循环，光遍历完一遍所有的还不够
for i in range(3):
    theta_m = theta_m - alpha_m * x[2*i:2*i+2].dot(x[2*i:2*i+2].dot(theta_m)-y[2*i:2*i+2])
    loss = np.power(x[2*i:2*i+2].dot(theta_m)-y[2*i:2*i+2],2).sum()/2
    print("loss:%f\n theta:"%loss,theta_m)

loss:0.000859
 theta: [[0.99363312]
 [1.01947748]]
loss:0.000152
 theta: [[0.99348694]
 [1.01919266]]
loss:0.000109
 theta: [[0.99416251]
 [1.02000887]]
